name: car_reference_book
description: Справочник автомобилиста

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  sqflite: ^2.2.7
  share: ^2.0.4
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
